---
read_interval: 1
output_path: ~/Dokumente/Thermometer/data/
sensors:
  - sensor: Dht22
    pin: 4
    description: Sensor A
  - sensor: Dht22
    pin: 17
    description: Sensor B
  - sensor: Dht22
    pin: 27
    description: Sensor C
cam:
  date_format: %H-%M-%S
  start: 08-00-00
  end: 20-00-00
